#Letter to myself😊

print('+------------------------------------------------------------------------------------+')
print("|                                                                                    |")
print("|                                                                        19-09-2023  |")
print("|            Hello! dear Nirmohi this is me from past i hope u  have achieved        |")
print("|     many things in your life. i hope that that u r leaving ur life  to the         |")
print("|     fullest. sorry if i have done any mistakes.but smile everytime.                |")
print("|     don't worry I promise to become a wishful person which we always wanted.       |")
print("|     be imagination. live in imagination. do work unimaginably.                     |")
print("|     love u .                                                                       |")
print("|                                                                                    |")
print("|     from ur past                                                                   |")
print("|     ur dear                                                                        |")
print("|     Nirmohi (╥﹏╥)                                                                 |")
print("|                                                                                    |")
print('+------------------------------------------------------------------------------------+')
